/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as InvestRouteImport } from './routes/invest'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ReferralsRouteImport } from './routes/referrals'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AdminCustodyRouteImport } from './routes/admin_.custody'
import { Route as AdminExitsRouteImport } from './routes/admin_.exits'
import { Route as AdminReferralsRouteImport } from './routes/admin_.referrals'
import { Route as AdminTradingRouteImport } from './routes/admin_.trading'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as AdminWalletsRouteImport } from './routes/admin_.wallets'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestRoute = InvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferralsRoute = ReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustodyRoute = AdminCustodyRouteImport.update({
  id: '/admin_/custody',
  path: '/admin/custody',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExitsRoute = AdminExitsRouteImport.update({
  id: '/admin_/exits',
  path: '/admin/exits',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReferralsRoute = AdminReferralsRouteImport.update({
  id: '/admin_/referrals',
  path: '/admin/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTradingRoute = AdminTradingRouteImport.update({
  id: '/admin_/trading',
  path: '/admin/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/admin_/wallets',
  path: '/admin/wallets',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/community': typeof CommunityRoute
  '/invest': typeof InvestRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/referrals': typeof ReferralsRoute
  '/signup': typeof SignupRoute
  '/trading': typeof TradingRoute
  '/wallet': typeof WalletRoute
  '/admin/custody': typeof AdminCustodyRoute
  '/admin/exits': typeof AdminExitsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/community': typeof CommunityRoute
  '/invest': typeof InvestRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/referrals': typeof ReferralsRoute
  '/signup': typeof SignupRoute
  '/trading': typeof TradingRoute
  '/wallet': typeof WalletRoute
  '/admin/custody': typeof AdminCustodyRoute
  '/admin/exits': typeof AdminExitsRoute
  '/admin/referrals': typeof AdminReferralsRoute
  '/admin/trading': typeof AdminTradingRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/wallets': typeof AdminWalletsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/community': typeof CommunityRoute
  '/invest': typeof InvestRoute
  '/ledger': typeof LedgerRoute
  '/login': typeof LoginRoute
  '/referrals': typeof ReferralsRoute
  '/signup': typeof SignupRoute
  '/trading': typeof TradingRoute
  '/wallet': typeof WalletRoute
  '/admin_/custody': typeof AdminCustodyRoute
  '/admin_/exits': typeof AdminExitsRoute
  '/admin_/referrals': typeof AdminReferralsRoute
  '/admin_/trading': typeof AdminTradingRoute
  '/admin_/users': typeof AdminUsersRoute
  '/admin_/wallets': typeof AdminWalletsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/community'
    | '/invest'
    | '/ledger'
    | '/login'
    | '/referrals'
    | '/signup'
    | '/trading'
    | '/wallet'
    | '/admin/custody'
    | '/admin/exits'
    | '/admin/referrals'
    | '/admin/trading'
    | '/admin/users'
    | '/admin/wallets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/community'
    | '/invest'
    | '/ledger'
    | '/login'
    | '/referrals'
    | '/signup'
    | '/trading'
    | '/wallet'
    | '/admin/custody'
    | '/admin/exits'
    | '/admin/referrals'
    | '/admin/trading'
    | '/admin/users'
    | '/admin/wallets'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/app'
    | '/community'
    | '/invest'
    | '/ledger'
    | '/login'
    | '/referrals'
    | '/signup'
    | '/trading'
    | '/wallet'
    | '/admin_/custody'
    | '/admin_/exits'
    | '/admin_/referrals'
    | '/admin_/trading'
    | '/admin_/users'
    | '/admin_/wallets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  CommunityRoute: typeof CommunityRoute
  InvestRoute: typeof InvestRoute
  LedgerRoute: typeof LedgerRoute
  LoginRoute: typeof LoginRoute
  ReferralsRoute: typeof ReferralsRoute
  SignupRoute: typeof SignupRoute
  TradingRoute: typeof TradingRoute
  WalletRoute: typeof WalletRoute
  AdminCustodyRoute: typeof AdminCustodyRoute
  AdminExitsRoute: typeof AdminExitsRoute
  AdminReferralsRoute: typeof AdminReferralsRoute
  AdminTradingRoute: typeof AdminTradingRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWalletsRoute: typeof AdminWalletsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invest': {
      id: '/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof InvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referrals': {
      id: '/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof ReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/custody': {
      id: '/admin_/custody'
      path: '/admin/custody'
      fullPath: '/admin/custody'
      preLoaderRoute: typeof AdminCustodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/exits': {
      id: '/admin_/exits'
      path: '/admin/exits'
      fullPath: '/admin/exits'
      preLoaderRoute: typeof AdminExitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/referrals': {
      id: '/admin_/referrals'
      path: '/admin/referrals'
      fullPath: '/admin/referrals'
      preLoaderRoute: typeof AdminReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/trading': {
      id: '/admin_/trading'
      path: '/admin/trading'
      fullPath: '/admin/trading'
      preLoaderRoute: typeof AdminTradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/wallets': {
      id: '/admin_/wallets'
      path: '/admin/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  CommunityRoute: CommunityRoute,
  InvestRoute: InvestRoute,
  LedgerRoute: LedgerRoute,
  LoginRoute: LoginRoute,
  ReferralsRoute: ReferralsRoute,
  SignupRoute: SignupRoute,
  TradingRoute: TradingRoute,
  WalletRoute: WalletRoute,
  AdminCustodyRoute: AdminCustodyRoute,
  AdminExitsRoute: AdminExitsRoute,
  AdminReferralsRoute: AdminReferralsRoute,
  AdminTradingRoute: AdminTradingRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWalletsRoute: AdminWalletsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
